name: exoplanet-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - pyarrow     
  - jupyter    
  - matplotlib  
  - seaborn     